### ISSUE TITLE
Python3.8 + RHEL8 + pip install krb5

### ISSUE THREAD

**Issue by gsantos1979** [jborean93/pykrb5#17]
Any ideas for this error? I'm trying to install using pip and using git clone + python setup but I get the same error.
Thank you.

      gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Isrc/krb5 -I/usr/include/python3.8 -c src/krb5/_context.c -o build/temp.linux-x86_64-cpython-38/src/krb5/_context.o -Werror -DHEIMDAL_XFREE
      src/krb5/_context.c: In function ‘krb5_free_default_realm_generic’:
      src/krb5/_context.c:790:9: error: implicit declaration of function ‘krb5_xfree’; did you mean ‘krb5_pac_free’? [-Werror=implicit-function-declaration]
               krb5_xfree(realm);
               ^~~~~~~~~~
               krb5_pac_free
      cc1: all warnings being treated as errors
      error: command '/bin/gcc' failed with exit code 1
      [end of output]

**Comment by jborean93** [comment]
Sorry for the delay in replying. This particular problem should have been fixed with https://github.com/jborean93/pykrb5/pull/18 as warnings are no longer treated as errors. It is perplexing that `krb5_xfree` is mentioned as that is a Heimdal only symbol and no longer part of MIT krb5 wich I assume RHEL8 users will use.
