### ISSUE TITLE
No binding for `krb5_cc_cache_match`

### ISSUE THREAD

**Issue by Jaakkonen** [jborean93/pykrb5#6]
I'm writing a Python implementation of `kinit` and it looks like the helper to check if there is a existing credential cache for a user (`krb5_cc_cache_match`) has no binding in this library.

`kinit.c` using this function: https://github.com/krb5/krb5/blob/master/src/clients/kinit/kinit.c#L537

**Comment by Jaakkonen** [comment]
It looks like that one was the only really required part missing. I got a minimal `kinit` clone working with `init_context`, `cc_resolve`, `cc_cache_match`, `get_init_creds_opt_alloc`, `get_init_creds_opt_set_out_ccache` and `get_init_creds_password`.

There are some minor things related to init options  such as `krb5_get_init_creds_opt_set_renew_life` but those are not required for the MVP `kinit` clone. Also renewing `krb5_get_renewed_creds` is missing but again that's not required for getting a ticket but only for renewing it.

**Comment by jborean93** [comment]
> There are some minor things related to init options such as krb5_get_init_creds_opt_set_renew_life but those are not required for the MVP kinit clone. Also renewing krb5_get_renewed_creds is missing but again that's not required for getting a ticket but only for renewing it.

Feel free to submit a PR if you are up to it, or request them. I can't guarantee I'll get to doing it as quick as I have this one but I will try my best.
