### ISSUE TITLE
Missing binding for `krb5_kt_add_entry`

### ISSUE THREAD

**Issue by 0xdeb** [jborean93/pykrb5#8]
Hi there, thanks for providing this library. 
I'm currently working on implementing a simple ipa-client in python and would like to save the keytab keys into a keytab file. 
In order for this to work the function `krb5_kt_add_entry` and structs `krb5_keytab_entry` and `krb5_keyblock` are needed. Can you implement this?

**Comment by jborean93** [comment]
You are free to try and implement them yourself, I probably won't be able to get to it for some time.

**Comment by jborean93** [comment]
I started looking into this and I think this might be harder than expected. While the APIs for `krb5_kt_add_entry` are the same for MIT and Heimdal the strcuts `krb5_keytab_entry` and possibly `krb5_keyblock` are different . On top of that, the way to populate the fields of `krb5_keytab_entry` seem to be quite different across both these providers. I'm hoping to have a closer look at this sometime soon but it's proving to be more troublesome than I thought it would be.
